name: gc_backend_ci

on:
  push:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.14.0'
      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint

      - name: Run build
        run: go build -v ./cmd/apiserver

      - name: Run lint
        run: |
          golint ./...

      - name: Run testing
        run: cd Tests && go test -v

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Heroku
        if: github.ref == 'refs/heads/dev'
        uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "back-xsolla-gc-dev"
          heroku_email: "wardenclock@gmail.com"

      - name: Deploy Production
        if: github.ref == 'refs/heads/master'
        uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "back-xsolla-gc"
          heroku_email: "wardenclock@gmail.com"