name: gc_backend_ci_tag

on:
  push:
    tags:
      - "v-*-*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.14.0'
      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint

      - name: Run build
        run: go build -v ./cmd/apiserver

      - name: Run lint
        run: |
          golint ./...

      - name: Run testing
        run: cd Tests && go test -v

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    if: success()
    steps:
      - uses: actions/checkout@v2
      - name: Get app name
        id: get_app_name
        run: |
          echo ::set-output name=APP_NAME::"back-xsolla-gc-${GITHUB_REF:10}"
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{ steps.get_app_name.outputs.APP_NAME }}
          heroku_email: "wardenclock@gmail.com"
